/*
 * Copyright 2017 by Noah Luskey <LuskeyNoah@gmail.com>
 *
 * This file is part of FreeWPC.
 *
 * FreeWPC is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * FreeWPC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with FreeWPC; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

/* Loops/Ramps: Handles the completion of shots with multiple switches 
 * The events generated by this file are:
 * EV_SHOT_AI_RAMP_MADE
 * EV_SHOT_CHASE_LOOP_MADE
 * EV_SHOT_CHASE_LOOP_TO_JETS
 * EV_SHOT_COMMAND_RAMP_MADE
 * EV_SHOT_ESCAPE_ROUTE_MADE
 * EV_SHOT_ESCAPE_ROUTE_TO_JETS
 */

#include <freewpc.h>

/* ball entered the AI ramp (left) */
CALLSET_ENTRY(shot_ai, SW_LEFT_RAMP_ENTRY)
{
    sound_send(SND_RAMP_ENTRY);
    event_can_follow(left_ramp_entry, left_ramp_made, TIME_1S);
}

/* ball completed the AI ramp (left) */
CALLSET_ENTRY(shot_ai, SW_LEFT_RAMP_MADE)
{
    if (event_did_follow(left_ramp_entry, left_ramp_made)) {
        callset_invoke(EV_SHOT_AI_RAMP_MADE);
    }
}
/* ball enetered the command ramp (right) */
CALLSET_ENTRY(shot_command, SW_RIGHT_RAMP_ENTRY)
{
    event_can_follow(right_ramp_entry, right_ramp_made, TIME_1S);
}

/* ball completed the command ramp (right) */
CALLSET_ENTRY(shot_command, SW_RIGHT_RAMP_MADE)
{
    if (event_did_follow(right_ramp_entry, right_ramp_made)) {
        callset_invoke(EV_SHOT_COMMAND_RAMP_MADE);
    }
}



/* chase loop event progression */
CALLSET_ENTRY(shot_chase, SW_LOWER_CHASE_LOOP)
{
    event_can_follow(chase_loop_enter_1, chase_loop_enter_2, TIME_100MS);
}

/* there are two switches in a row
TODO: deal with the fact that of the two may be broken and that's ok */
CALLSET_ENTRY(shot_chase, SW_UPPER_CHASE_LOOP)
{
    if (event_did_follow(chase_loop_enter_1, chase_loop_enter_2)) {
        event_can_follow(chase_loop_enter_2, chase_loop_complete, TIME_500MS);
        event_can_follow(chase_loop_enter_2, chase_loop_to_jets, TIME_500MS);
    }
}

/* there are also two switches in a row coming down the escape route
but it doesn't matter if only one is it */
// TODO: make sure this only triggers once per loop made
CALLSET_ENTRY(shot_chase, SW_UPPER_ESCAPE_ROUTE, SW_LOWER_ESCAPE_ROUTE)
{
    if (event_did_follow(chase_loop_enter_2, chase_loop_complete)) {
        callset_invoke(EV_SHOT_CHASE_LOOP_MADE);
    }
}

/* if a ball was just kicked out of the top lock, don't confuse this for an incomplete loop shot */
CALLSET_ENTRY(shot, dev_top_lock_kick_success) {
        timer_restart_free(GID_BLOCK_SHOTS_TO_JETS, TIME_5S);
}

/* This covers both the chase loop and the escape route falling into the lanes */
CALLSET_ENTRY(shot, SW_TOP_LANE_LEFT, SW_TOP_LANE_CENTER, SW_TOP_LANE_RIGHT)
{
    /* was a ball recently fired out of the top lock? Don't fire these events */
    if (task_find_gid(GID_BLOCK_SHOTS_TO_JETS)) {
        return;
    }
    
    if (event_did_follow(chase_loop_enter_2, chase_loop_to_jets)) {
        callset_invoke(EV_SHOT_CHASE_LOOP_TO_JETS);
    } else if (event_did_follow(escape_route_enter_2, escape_route_to_jets)) {
        callset_invoke(EV_SHOT_ESCAPE_ROUTE_TO_JETS);
    }
}



/* escape route progression */
CALLSET_ENTRY(shot_escape, SW_LOWER_ESCAPE_ROUTE)
{
    event_can_follow(escape_route_enter_1, escape_route_enter_2, TIME_100MS);
}

/* escape route has two switches, apparently */
CALLSET_ENTRY(shot_escape, SW_UPPER_ESCAPE_ROUTE)
{
    sound_send(SND_REVVING);
    if (event_did_follow(escape_route_enter_1, escape_route_enter_2)) {
        event_can_follow(escape_route_enter_2, escape_route_complete, TIME_1S);
        event_can_follow(escape_route_enter_2, escape_route_to_jets, TIME_2S);
    }
}

/* escape route to the hole */
CALLSET_ENTRY(shot_escape, SW_TOP_LOCK)
{
    if (event_did_follow(escape_route_enter_2, escape_route_complete)) {
        /* start a timer that blocks the escape route to jets event */
        callset_invoke(EV_SHOT_ESCAPE_ROUTE_MADE);
    }
}


/* things won't compile if these don't exist somewhere in the code at least once */
CALLSET_ENTRY(shots, EV_SHOT_COMMAND_RAMP_MADE) {sound_send(SND_RAMP_MADE);}
CALLSET_ENTRY(shots, EV_SHOT_AI_RAMP_MADE) {sound_send(SND_RAMP_MADE);}
CALLSET_ENTRY(shots, EV_SHOT_CHASE_LOOP_MADE) {sound_send(SND_BIKE_1);}
CALLSET_ENTRY(shots, EV_SHOT_CHASE_LOOP_TO_JETS) {sound_send(SND_BIKE_2);}
CALLSET_ENTRY(shots, EV_SHOT_ESCAPE_ROUTE_MADE) {sound_send(SND_LOOP);}
CALLSET_ENTRY(shots, EV_SHOT_ESCAPE_ROUTE_TO_JETS) {sound_send(SND_BOOM);}